//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HesapMakinesi.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Gecmis
    {
        public int id { get; set; }
        public System.DateTime tarih { get; set; }
        public double sayi1 { get; set; }
        public double sayi2 { get; set; }
        public double islemler { get; set; }
        public string sonuc { get; set; }
    }
}
